const gamesData = {
    // 4 games only - Calculated Probability 85%+
    topSecret: [
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Real Madrid",
            teamB: "Man City",
            prediction: "Over 2.5 Goals",
            odds: "1.45",
            confidence: "92%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "B Dortmund",
            teamB: "Bodo/Glimt",
            prediction: "Home Win & Over 2.5 Goals",
            odds: "1.50",
            confidence: "90%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Athletic Bilbao",
            teamB: "Paris St-Germain",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.65",
            confidence: "88%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "20:45",
            date: "10.12.2025",
            teamA: "Ipswich",
            teamB: "Stoke",
            prediction: "Home Win or Draw (1X)",
            odds: "1.30",
            confidence: "85%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // 3 games only - Strong Value Bets (higher odds/slight risk)
    ultimate: [
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "B Leverkusen",
            teamB: "Newcastle",
            prediction: "Home Win",
            odds: "1.80",
            confidence: "78%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "20:45",
            date: "10.12.2025",
            teamA: "Bristol C",
            teamB: "Leicester",
            prediction: "Under 2.5 Goals",
            odds: "1.75",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Club Brugge",
            teamB: "Arsenal",
            prediction: "Away Win",
            odds: "1.90",
            confidence: "70%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // 3 games only - Solid Predictions (accumulator staples)
    free: [
        {
            league: "UEFA Champions League",
            time: "20:45",
            date: "10.12.2025",
            teamA: "Villarreal",
            teamB: "Copenhagen",
            prediction: "Home Win",
            odds: "1.35",
            confidence: "88%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "20:45",
            date: "10.12.2025",
            teamA: "Derby",
            teamB: "Millwall",
            prediction: "Home Win or Draw (1X)",
            odds: "1.45",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "21:00",
            date: "10.12.2025",
            teamA: "Hull",
            teamB: "Wrexham",
            prediction: "Over 1.5 Goals",
            odds: "1.25",
            confidence: "80%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // Maximum 5 games - Best Goal Market Picks
    overUnder: [
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Real Madrid",
            teamB: "Man City",
            prediction: "Over 3.5 Goals",
            odds: "2.10",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Benfica",
            teamB: "Napoli",
            prediction: "Over 2.5 Goals",
            odds: "1.95",
            confidence: "78%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "B Dortmund",
            teamB: "Bodo/Glimt",
            prediction: "Over 3.5 Goals",
            odds: "2.05",
            confidence: "70%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "20:45",
            date: "10.12.2025",
            teamA: "Derby",
            teamB: "Millwall",
            prediction: "Under 2.5 Goals",
            odds: "1.75",
            confidence: "78%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "20:45",
            date: "10.12.2025",
            teamA: "Qarabag",
            teamB: "Ajax",
            prediction: "Over 2.5 Goals",
            odds: "1.85",
            confidence: "72%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // 4 games only - Best BTTS Opportunities
    btts: [
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Real Madrid",
            teamB: "Man City",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.55",
            confidence: "85%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Benfica",
            teamB: "Napoli",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.70",
            confidence: "80%",
            status: "pending",
            isLive: false,
        },
        {
            league: "UEFA Champions League",
            time: "23:00",
            date: "10.12.2025",
            teamA: "Athletic Bilbao",
            teamB: "Paris St-Germain",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.65",
            confidence: "78%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "21:00",
            date: "10.12.2025",
            teamA: "Hull",
            teamB: "Wrexham",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.75",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
    ]
};
