const gamesData = {
    // 4 games only - Calculated Probability 85%+ (Bankers)
    topSecret: [
        {
            league: "Serie A",
            time: "20:45",
            date: "23.01.2026",
            teamA: "Inter Milan",
            teamB: "Pisa",
            prediction: "Home Win",
            odds: "1.28",
            confidence: "94%",
            status: "pending",
            isLive: false,
        },
        {
            league: "CAF Champions League",
            time: "19:00",
            date: "23.01.2026",
            teamA: "Al Ahly",
            teamB: "Young Africans",
            prediction: "Home Win",
            odds: "1.35",
            confidence: "89%",
            status: "pending",
            isLive: false,
        },
        {
            league: "CAF Champions League",
            time: "21:00",
            date: "23.01.2026",
            teamA: "Mamelodi Sundowns",
            teamB: "Al Hilal Omdurman",
            prediction: "Home Win",
            odds: "1.40",
            confidence: "87%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Bundesliga",
            time: "20:30",
            date: "23.01.2026",
            teamA: "St. Pauli",
            teamB: "Hamburger SV",
            prediction: "Over 1.5 Goals",
            odds: "1.25",
            confidence: "86%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // 3 games only - Strong Value Bets (Higher Odds/Slight Risk)
    ultimate: [
        {
            league: "Championship",
            time: "20:00",
            date: "23.01.2026",
            teamA: "Derby County",
            teamB: "West Brom",
            prediction: "Home Win",
            odds: "2.40",
            confidence: "70%",
            status: "pending",
            isLive: false,
        },
        {
            league: "La Liga",
            time: "21:00",
            date: "23.01.2026",
            teamA: "Levante",
            teamB: "Elche",
            prediction: "Draw",
            odds: "3.20",
            confidence: "60%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Bundesliga",
            time: "20:30",
            date: "23.01.2026",
            teamA: "St. Pauli",
            teamB: "Hamburger SV",
            prediction: "Draw or Away Win (X2)",
            odds: "1.75",
            confidence: "72%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // 3 games only - Solid Predictions (Accumulator Staples)
    free: [
        {
            league: "Championship",
            time: "20:00",
            date: "23.01.2026",
            teamA: "Derby County",
            teamB: "West Brom",
            prediction: "Home Win or Draw (1X)",
            odds: "1.45",
            confidence: "82%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Serie A",
            time: "20:45",
            date: "23.01.2026",
            teamA: "Inter Milan",
            teamB: "Pisa",
            prediction: "Inter to Score Over 1.5 Goals",
            odds: "1.40",
            confidence: "88%",
            status: "pending",
            isLive: false,
        },
        {
            league: "La Liga",
            time: "21:00",
            date: "23.01.2026",
            teamA: "Levante",
            teamB: "Elche",
            prediction: "Under 3.5 Goals",
            odds: "1.28",
            confidence: "85%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // Maximum 5 games - Best Goal Market Picks
    overUnder: [
        {
            league: "Bundesliga",
            time: "20:30",
            date: "23.01.2026",
            teamA: "St. Pauli",
            teamB: "Hamburger SV",
            prediction: "Over 2.5 Goals",
            odds: "1.85",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Serie A",
            time: "20:45",
            date: "23.01.2026",
            teamA: "Inter Milan",
            teamB: "Pisa",
            prediction: "Over 2.5 Goals",
            odds: "1.65",
            confidence: "80%",
            status: "pending",
            isLive: false,
        },
        {
            league: "La Liga",
            time: "21:00",
            date: "23.01.2026",
            teamA: "Levante",
            teamB: "Elche",
            prediction: "Under 2.5 Goals",
            odds: "1.70",
            confidence: "72%",
            status: "pending",
            isLive: false,
        },
        {
            league: "CAF Champions League",
            time: "19:00",
            date: "23.01.2026",
            teamA: "Al Ahly",
            teamB: "Young Africans",
            prediction: "Over 2.5 Goals",
            odds: "1.90",
            confidence: "70%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "20:00",
            date: "23.01.2026",
            teamA: "Derby County",
            teamB: "West Brom",
            prediction: "Under 3.5 Goals",
            odds: "1.30",
            confidence: "80%",
            status: "pending",
            isLive: false,
        },
    ],
    
    // 4 games only - Best BTTS Opportunities
    btts: [
        {
            league: "Bundesliga",
            time: "20:30",
            date: "23.01.2026",
            teamA: "St. Pauli",
            teamB: "Hamburger SV",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.60",
            confidence: "82%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Championship",
            time: "20:00",
            date: "23.01.2026",
            teamA: "Derby County",
            teamB: "West Brom",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.80",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Serie A",
            time: "20:45",
            date: "23.01.2026",
            teamA: "Inter Milan",
            teamB: "Pisa",
            prediction: "Both Teams To Score (No)",
            odds: "1.75",
            confidence: "65%",
            status: "pending",
            isLive: false,
        },
        {
            league: "La Liga",
            time: "21:00",
            date: "23.01.2026",
            teamA: "Levante",
            teamB: "Elche",
            prediction: "Both Teams To Score (No)",
            odds: "1.85",
            confidence: "68%",
            status: "pending",
            isLive: false,
        },
    ]
};
