const gamesData = {
    // --- topSecret: 4 games only (ULTRA HIGH CONFIDENCE, 85%+ Calculated Probability) ---
    topSecret: [
        {
            league: "Turkish Süper Lig",
            time: "17:00",
            date: "05.12.2025",
            teamA: "Galatasaray",
            teamB: "Samsunspor",
            prediction: "Home Win (1)",
            odds: "1.28",
            confidence: "90%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Czech First League",
            time: "20:30",
            date: "05.12.2025",
            teamA: "Teplice",
            teamB: "Slavia Prague",
            prediction: "Away Win (2) - Asian Handicap -1.5",
            odds: "1.85",
            confidence: "88%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Northern Irish Premiership",
            time: "19:45",
            date: "05.12.2025",
            teamA: "Larne",
            teamB: "Linfield",
            prediction: "Home Win (1) & Over 1.5 Goals",
            odds: "1.50",
            confidence: "87%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Welsh Premier League",
            time: "19:45",
            date: "05.12.2025",
            teamA: "Cardiff Metropolitan University",
            teamB: "Llanelli Town",
            prediction: "Home Win (1) & Over 2.5 Goals",
            odds: "1.35",
            confidence: "92%",
            status: "pending",
            isLive: false,
        },
    ],

    // --- ultimate: 3 games only (STRONG VALUE BETS, 70-85% Calculated Probability) ---
    ultimate: [
        {
            league: "German 2. Bundesliga",
            time: "17:30",
            date: "05.12.2025",
            teamA: "Fortuna Düsseldorf",
            teamB: "Schalke 04",
            prediction: "Home Win (1)",
            odds: "2.10",
            confidence: "78%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Polish Ekstraklasa",
            time: "19:30",
            date: "05.12.2025",
            teamA: "Lechia Gdansk",
            teamB: "Gornik Zabrze",
            prediction: "Draw No Bet - Lechia Gdansk",
            odds: "1.75",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Scottish Championship",
            time: "19:45",
            date: "05.12.2025",
            teamA: "Morton",
            teamB: "Queen's Park",
            prediction: "Home Win (1)",
            odds: "1.65",
            confidence: "82%",
            status: "pending",
            isLive: false,
        },
    ],

    // --- free: 3 games only (SOLID PREDICTIONS) ---
    free: [
        {
            league: "Russian Premier League",
            time: "19:30",
            date: "05.12.2025",
            teamA: "Terek Grozny",
            teamB: "Gazovik Orenburg",
            prediction: "Home Win or Draw (1X)",
            odds: "1.45",
            confidence: "70%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Australian A-League Men",
            time: "08:35",
            date: "05.12.2025",
            teamA: "Macarthur FC",
            teamB: "Melbourne Victory",
            prediction: "Over 2.5 Goals",
            odds: "1.68",
            confidence: "74%",
            status: "pending",
            isLive: false,
        },
        {
            league: "English Championship",
            time: "20:00",
            date: "05.12.2025",
            teamA: "Hull City",
            teamB: "Middlesbrough",
            prediction: "Home Win or Draw (1X)",
            odds: "1.55",
            confidence: "68%",
            status: "pending",
            isLive: false,
        },
    ],

    // --- overUnder: Maximum 5 games (BEST GOAL MARKET PICKS) ---
    overUnder: [
        {
            league: "Portuguese Primeira Liga",
            time: "20:15",
            date: "05.12.2025",
            teamA: "Benfica",
            teamB: "Sporting CP",
            prediction: "Over 2.5 Goals",
            odds: "1.70",
            confidence: "78%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Turkish Süper Lig",
            time: "17:00",
            date: "05.12.2025",
            teamA: "Galatasaray",
            teamB: "Samsunspor",
            prediction: "Over 2.5 Goals",
            odds: "1.40",
            confidence: "85%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Dutch Eredivisie",
            time: "20:00",
            date: "05.12.2025",
            teamA: "Excelsior",
            teamB: "FC Groningen",
            prediction: "Over 2.5 Goals",
            odds: "1.65",
            confidence: "75%",
            status: "pending",
            isLive: false,
        },
        {
            league: "German Bundesliga",
            time: "19:30",
            date: "05.12.2025",
            teamA: "Mainz 05",
            teamB: "Borussia M'gladbach",
            prediction: "Over 2.5 Goals",
            odds: "1.78",
            confidence: "76%",
            status: "pending",
            isLive: false,
        },
        {
            league: "Spanish La Liga 2",
            time: "20:00",
            date: "05.12.2025",
            teamA: "Real Oviedo",
            teamB: "RCD Mallorca",
            prediction: "Under 2.5 Goals",
            odds: "1.55",
            confidence: "80%",
            status: "pending",
            isLive: false,
        },
    ],

    // --- btts: 4 games only (BEST BTTS OPPORTUNITIES) ---
    btts: [
        {
            league: "German Bundesliga",
            time: "19:30",
            date: "05.12.2025",
            teamA: "Mainz 05",
            teamB: "Borussia M'gladbach",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.68",
            confidence: "79%",
            status: "pending",
            isLive: false,
        },
        {
            league: "English FA Cup",
            time: "19:30",
            date: "05.12.2025",
            teamA: "Salford City",
            teamB: "Leyton Orient",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.75",
            confidence: "73%",
            status: "pending",
            isLive: false,
        },
        {
            league: "English Championship",
            time: "20:00",
            date: "05.12.2025",
            teamA: "Hull City",
            teamB: "Middlesbrough",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.85",
            confidence: "70%",
            status: "pending",
            isLive: false,
        },
        {
            league: "French Ligue 1",
            time: "18:00",
            date: "05.12.2025",
            teamA: "Brest",
            teamB: "AS Monaco",
            prediction: "Both Teams To Score (Yes)",
            odds: "1.62",
            confidence: "77%",
            status: "pending",
            isLive: false,
        },
    ]
};
